Domain - Botany

Problem Statement - Measurements of geometrical properties of kernels belonging to three different varieties of wheat. We will use the data to train a classification model.

Metric - We will use accuracy to assess the model

Data Summary - The examined group comprised kernels belonging to three different varieties of wheat: Kama, Rosa and Canadian, 70 elements each, randomly selected for 
the experiment. High quality visualization of the internal kernel structure was detected using a soft X-ray technique. It is non-destructive and considerably cheaper than other more sophisticated imaging techniques like scanning microscopy or laser technology. The images were recorded on 13x18 cm X-ray KODAK plates.

Solution Proposal - Logistica Regression

Benchmark Model - Guess all Kama

Plan - Load the data, visualize the data, feature selection, train-test split, assess the model

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

%matplotlib inline

In [7]:
problem_df = pd.read_csv('seeds_dataset.csv', index_col=0, header=None)

In [8]:
problem_df.describe()

,1,2,3,4,5,6,7,8,9
count,210.000000,207.000000,210.000000,209.000000,210.000000,206.000000,206.000000,10.000000,2.0
mean,14.559286,0.871280,5.563918,3.281440,3.693530,5.407529,2.084039,2.644300,1.0
std,1.305959,0.023306,0.719594,0.419907,1.495112,0.532330,0.948211,1.278151,0.0
min,12.410000,0.808100,0.818900,2.630000,0.765100,3.485000,1.000000,1.000000,1.0
25%,13.450000,0.857700,5.244750,2.956000,2.600250,5.045000,1.000000,2.000000,1.0
50%,14.320000,0.873500,5.518000,3.245000,3.599000,5.226000,2.000000,3.000000,1.0
75%,15.715000,0.887650,5.979750,3.566000,4.768750,5.879000,3.000000,3.000000,1.0
max,17.250000,0.918300,6.675000,5.325000,8.456000,6.735000,5.439000,5.443000,1.0